# fly.toml file generated for chart89-mysql-test on 2023-08-13T18:11:38-04:00

app = "chart89-mysql-test"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "iad"

[processes]
app = "--datadir /data/mysql --default-authentication-plugin mysql_native_password --performance-schema=OFF --innodb-buffer-pool-size 64M"

[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "UniRouteDB"
  MYSQL_USER = "non_root_user"

[build]
  image = "mysql:8.0.32"